/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicGenerateScriptsRouteImport } from './routes/api/public/generate-scripts'
import { Route as ApiPublicExtractUrlRouteImport } from './routes/api/public/extract-url'
import { Route as ApiPublicHeygenVoicesRouteImport } from './routes/api/public/heygen/voices'
import { Route as ApiPublicHeygenGenerateRouteImport } from './routes/api/public/heygen/generate'
import { Route as ApiPublicHeygenAvatarsRouteImport } from './routes/api/public/heygen/avatars'
import { Route as ApiPublicHeygenStatusVideoIdRouteImport } from './routes/api/public/heygen/status.$videoId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGenerateScriptsRoute =
  ApiPublicGenerateScriptsRouteImport.update({
    id: '/api/public/generate-scripts',
    path: '/api/public/generate-scripts',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicExtractUrlRoute = ApiPublicExtractUrlRouteImport.update({
  id: '/api/public/extract-url',
  path: '/api/public/extract-url',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHeygenVoicesRoute = ApiPublicHeygenVoicesRouteImport.update({
  id: '/api/public/heygen/voices',
  path: '/api/public/heygen/voices',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHeygenGenerateRoute = ApiPublicHeygenGenerateRouteImport.update({
  id: '/api/public/heygen/generate',
  path: '/api/public/heygen/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHeygenAvatarsRoute = ApiPublicHeygenAvatarsRouteImport.update({
  id: '/api/public/heygen/avatars',
  path: '/api/public/heygen/avatars',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHeygenStatusVideoIdRoute =
  ApiPublicHeygenStatusVideoIdRouteImport.update({
    id: '/api/public/heygen/status/$videoId',
    path: '/api/public/heygen/status/$videoId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/extract-url': typeof ApiPublicExtractUrlRoute
  '/api/public/generate-scripts': typeof ApiPublicGenerateScriptsRoute
  '/api/public/heygen/avatars': typeof ApiPublicHeygenAvatarsRoute
  '/api/public/heygen/generate': typeof ApiPublicHeygenGenerateRoute
  '/api/public/heygen/voices': typeof ApiPublicHeygenVoicesRoute
  '/api/public/heygen/status/$videoId': typeof ApiPublicHeygenStatusVideoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/extract-url': typeof ApiPublicExtractUrlRoute
  '/api/public/generate-scripts': typeof ApiPublicGenerateScriptsRoute
  '/api/public/heygen/avatars': typeof ApiPublicHeygenAvatarsRoute
  '/api/public/heygen/generate': typeof ApiPublicHeygenGenerateRoute
  '/api/public/heygen/voices': typeof ApiPublicHeygenVoicesRoute
  '/api/public/heygen/status/$videoId': typeof ApiPublicHeygenStatusVideoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/extract-url': typeof ApiPublicExtractUrlRoute
  '/api/public/generate-scripts': typeof ApiPublicGenerateScriptsRoute
  '/api/public/heygen/avatars': typeof ApiPublicHeygenAvatarsRoute
  '/api/public/heygen/generate': typeof ApiPublicHeygenGenerateRoute
  '/api/public/heygen/voices': typeof ApiPublicHeygenVoicesRoute
  '/api/public/heygen/status/$videoId': typeof ApiPublicHeygenStatusVideoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/public/extract-url'
    | '/api/public/generate-scripts'
    | '/api/public/heygen/avatars'
    | '/api/public/heygen/generate'
    | '/api/public/heygen/voices'
    | '/api/public/heygen/status/$videoId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/public/extract-url'
    | '/api/public/generate-scripts'
    | '/api/public/heygen/avatars'
    | '/api/public/heygen/generate'
    | '/api/public/heygen/voices'
    | '/api/public/heygen/status/$videoId'
  id:
    | '__root__'
    | '/'
    | '/api/public/extract-url'
    | '/api/public/generate-scripts'
    | '/api/public/heygen/avatars'
    | '/api/public/heygen/generate'
    | '/api/public/heygen/voices'
    | '/api/public/heygen/status/$videoId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicExtractUrlRoute: typeof ApiPublicExtractUrlRoute
  ApiPublicGenerateScriptsRoute: typeof ApiPublicGenerateScriptsRoute
  ApiPublicHeygenAvatarsRoute: typeof ApiPublicHeygenAvatarsRoute
  ApiPublicHeygenGenerateRoute: typeof ApiPublicHeygenGenerateRoute
  ApiPublicHeygenVoicesRoute: typeof ApiPublicHeygenVoicesRoute
  ApiPublicHeygenStatusVideoIdRoute: typeof ApiPublicHeygenStatusVideoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/generate-scripts': {
      id: '/api/public/generate-scripts'
      path: '/api/public/generate-scripts'
      fullPath: '/api/public/generate-scripts'
      preLoaderRoute: typeof ApiPublicGenerateScriptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/extract-url': {
      id: '/api/public/extract-url'
      path: '/api/public/extract-url'
      fullPath: '/api/public/extract-url'
      preLoaderRoute: typeof ApiPublicExtractUrlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/heygen/voices': {
      id: '/api/public/heygen/voices'
      path: '/api/public/heygen/voices'
      fullPath: '/api/public/heygen/voices'
      preLoaderRoute: typeof ApiPublicHeygenVoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/heygen/generate': {
      id: '/api/public/heygen/generate'
      path: '/api/public/heygen/generate'
      fullPath: '/api/public/heygen/generate'
      preLoaderRoute: typeof ApiPublicHeygenGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/heygen/avatars': {
      id: '/api/public/heygen/avatars'
      path: '/api/public/heygen/avatars'
      fullPath: '/api/public/heygen/avatars'
      preLoaderRoute: typeof ApiPublicHeygenAvatarsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/heygen/status/$videoId': {
      id: '/api/public/heygen/status/$videoId'
      path: '/api/public/heygen/status/$videoId'
      fullPath: '/api/public/heygen/status/$videoId'
      preLoaderRoute: typeof ApiPublicHeygenStatusVideoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicExtractUrlRoute: ApiPublicExtractUrlRoute,
  ApiPublicGenerateScriptsRoute: ApiPublicGenerateScriptsRoute,
  ApiPublicHeygenAvatarsRoute: ApiPublicHeygenAvatarsRoute,
  ApiPublicHeygenGenerateRoute: ApiPublicHeygenGenerateRoute,
  ApiPublicHeygenVoicesRoute: ApiPublicHeygenVoicesRoute,
  ApiPublicHeygenStatusVideoIdRoute: ApiPublicHeygenStatusVideoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
