/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicGenerateScriptsRouteImport } from './routes/api/public/generate-scripts'
import { Route as ApiPublicExtractUrlRouteImport } from './routes/api/public/extract-url'
import { Route as ApiPublicHeygenVoicesRouteImport } from './routes/api/public/heygen/voices'
import { Route as ApiPublicHeygenGenerateWithAudioRouteImport } from './routes/api/public/heygen/generate-with-audio'
import { Route as ApiPublicHeygenGenerateRouteImport } from './routes/api/public/heygen/generate'
import { Route as ApiPublicHeygenAvatarsRouteImport } from './routes/api/public/heygen/avatars'
import { Route as ApiPublicElevenlabsTranscribeRouteImport } from './routes/api/public/elevenlabs/transcribe'
import { Route as ApiPublicElevenlabsCloneVoiceRouteImport } from './routes/api/public/elevenlabs/clone-voice'
import { Route as ApiPublicHeygenStatusVideoIdRouteImport } from './routes/api/public/heygen/status.$videoId'
import { Route as ApiPublicHeygenPhotoAvatarCreateRouteImport } from './routes/api/public/heygen/photo-avatar.create'
import { Route as ApiPublicHeygenPhotoAvatarStatusGroupIdRouteImport } from './routes/api/public/heygen/photo-avatar.status.$groupId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGenerateScriptsRoute =
  ApiPublicGenerateScriptsRouteImport.update({
    id: '/api/public/generate-scripts',
    path: '/api/public/generate-scripts',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicExtractUrlRoute = ApiPublicExtractUrlRouteImport.update({
  id: '/api/public/extract-url',
  path: '/api/public/extract-url',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHeygenVoicesRoute = ApiPublicHeygenVoicesRouteImport.update({
  id: '/api/public/heygen/voices',
  path: '/api/public/heygen/voices',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHeygenGenerateWithAudioRoute =
  ApiPublicHeygenGenerateWithAudioRouteImport.update({
    id: '/api/public/heygen/generate-with-audio',
    path: '/api/public/heygen/generate-with-audio',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHeygenGenerateRoute = ApiPublicHeygenGenerateRouteImport.update({
  id: '/api/public/heygen/generate',
  path: '/api/public/heygen/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHeygenAvatarsRoute = ApiPublicHeygenAvatarsRouteImport.update({
  id: '/api/public/heygen/avatars',
  path: '/api/public/heygen/avatars',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicElevenlabsTranscribeRoute =
  ApiPublicElevenlabsTranscribeRouteImport.update({
    id: '/api/public/elevenlabs/transcribe',
    path: '/api/public/elevenlabs/transcribe',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicElevenlabsCloneVoiceRoute =
  ApiPublicElevenlabsCloneVoiceRouteImport.update({
    id: '/api/public/elevenlabs/clone-voice',
    path: '/api/public/elevenlabs/clone-voice',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHeygenStatusVideoIdRoute =
  ApiPublicHeygenStatusVideoIdRouteImport.update({
    id: '/api/public/heygen/status/$videoId',
    path: '/api/public/heygen/status/$videoId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHeygenPhotoAvatarCreateRoute =
  ApiPublicHeygenPhotoAvatarCreateRouteImport.update({
    id: '/api/public/heygen/photo-avatar/create',
    path: '/api/public/heygen/photo-avatar/create',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHeygenPhotoAvatarStatusGroupIdRoute =
  ApiPublicHeygenPhotoAvatarStatusGroupIdRouteImport.update({
    id: '/api/public/heygen/photo-avatar/status/$groupId',
    path: '/api/public/heygen/photo-avatar/status/$groupId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/extract-url': typeof ApiPublicExtractUrlRoute
  '/api/public/generate-scripts': typeof ApiPublicGenerateScriptsRoute
  '/api/public/elevenlabs/clone-voice': typeof ApiPublicElevenlabsCloneVoiceRoute
  '/api/public/elevenlabs/transcribe': typeof ApiPublicElevenlabsTranscribeRoute
  '/api/public/heygen/avatars': typeof ApiPublicHeygenAvatarsRoute
  '/api/public/heygen/generate': typeof ApiPublicHeygenGenerateRoute
  '/api/public/heygen/generate-with-audio': typeof ApiPublicHeygenGenerateWithAudioRoute
  '/api/public/heygen/voices': typeof ApiPublicHeygenVoicesRoute
  '/api/public/heygen/photo-avatar/create': typeof ApiPublicHeygenPhotoAvatarCreateRoute
  '/api/public/heygen/status/$videoId': typeof ApiPublicHeygenStatusVideoIdRoute
  '/api/public/heygen/photo-avatar/status/$groupId': typeof ApiPublicHeygenPhotoAvatarStatusGroupIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/extract-url': typeof ApiPublicExtractUrlRoute
  '/api/public/generate-scripts': typeof ApiPublicGenerateScriptsRoute
  '/api/public/elevenlabs/clone-voice': typeof ApiPublicElevenlabsCloneVoiceRoute
  '/api/public/elevenlabs/transcribe': typeof ApiPublicElevenlabsTranscribeRoute
  '/api/public/heygen/avatars': typeof ApiPublicHeygenAvatarsRoute
  '/api/public/heygen/generate': typeof ApiPublicHeygenGenerateRoute
  '/api/public/heygen/generate-with-audio': typeof ApiPublicHeygenGenerateWithAudioRoute
  '/api/public/heygen/voices': typeof ApiPublicHeygenVoicesRoute
  '/api/public/heygen/photo-avatar/create': typeof ApiPublicHeygenPhotoAvatarCreateRoute
  '/api/public/heygen/status/$videoId': typeof ApiPublicHeygenStatusVideoIdRoute
  '/api/public/heygen/photo-avatar/status/$groupId': typeof ApiPublicHeygenPhotoAvatarStatusGroupIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/extract-url': typeof ApiPublicExtractUrlRoute
  '/api/public/generate-scripts': typeof ApiPublicGenerateScriptsRoute
  '/api/public/elevenlabs/clone-voice': typeof ApiPublicElevenlabsCloneVoiceRoute
  '/api/public/elevenlabs/transcribe': typeof ApiPublicElevenlabsTranscribeRoute
  '/api/public/heygen/avatars': typeof ApiPublicHeygenAvatarsRoute
  '/api/public/heygen/generate': typeof ApiPublicHeygenGenerateRoute
  '/api/public/heygen/generate-with-audio': typeof ApiPublicHeygenGenerateWithAudioRoute
  '/api/public/heygen/voices': typeof ApiPublicHeygenVoicesRoute
  '/api/public/heygen/photo-avatar/create': typeof ApiPublicHeygenPhotoAvatarCreateRoute
  '/api/public/heygen/status/$videoId': typeof ApiPublicHeygenStatusVideoIdRoute
  '/api/public/heygen/photo-avatar/status/$groupId': typeof ApiPublicHeygenPhotoAvatarStatusGroupIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/public/extract-url'
    | '/api/public/generate-scripts'
    | '/api/public/elevenlabs/clone-voice'
    | '/api/public/elevenlabs/transcribe'
    | '/api/public/heygen/avatars'
    | '/api/public/heygen/generate'
    | '/api/public/heygen/generate-with-audio'
    | '/api/public/heygen/voices'
    | '/api/public/heygen/photo-avatar/create'
    | '/api/public/heygen/status/$videoId'
    | '/api/public/heygen/photo-avatar/status/$groupId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/public/extract-url'
    | '/api/public/generate-scripts'
    | '/api/public/elevenlabs/clone-voice'
    | '/api/public/elevenlabs/transcribe'
    | '/api/public/heygen/avatars'
    | '/api/public/heygen/generate'
    | '/api/public/heygen/generate-with-audio'
    | '/api/public/heygen/voices'
    | '/api/public/heygen/photo-avatar/create'
    | '/api/public/heygen/status/$videoId'
    | '/api/public/heygen/photo-avatar/status/$groupId'
  id:
    | '__root__'
    | '/'
    | '/api/public/extract-url'
    | '/api/public/generate-scripts'
    | '/api/public/elevenlabs/clone-voice'
    | '/api/public/elevenlabs/transcribe'
    | '/api/public/heygen/avatars'
    | '/api/public/heygen/generate'
    | '/api/public/heygen/generate-with-audio'
    | '/api/public/heygen/voices'
    | '/api/public/heygen/photo-avatar/create'
    | '/api/public/heygen/status/$videoId'
    | '/api/public/heygen/photo-avatar/status/$groupId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicExtractUrlRoute: typeof ApiPublicExtractUrlRoute
  ApiPublicGenerateScriptsRoute: typeof ApiPublicGenerateScriptsRoute
  ApiPublicElevenlabsCloneVoiceRoute: typeof ApiPublicElevenlabsCloneVoiceRoute
  ApiPublicElevenlabsTranscribeRoute: typeof ApiPublicElevenlabsTranscribeRoute
  ApiPublicHeygenAvatarsRoute: typeof ApiPublicHeygenAvatarsRoute
  ApiPublicHeygenGenerateRoute: typeof ApiPublicHeygenGenerateRoute
  ApiPublicHeygenGenerateWithAudioRoute: typeof ApiPublicHeygenGenerateWithAudioRoute
  ApiPublicHeygenVoicesRoute: typeof ApiPublicHeygenVoicesRoute
  ApiPublicHeygenPhotoAvatarCreateRoute: typeof ApiPublicHeygenPhotoAvatarCreateRoute
  ApiPublicHeygenStatusVideoIdRoute: typeof ApiPublicHeygenStatusVideoIdRoute
  ApiPublicHeygenPhotoAvatarStatusGroupIdRoute: typeof ApiPublicHeygenPhotoAvatarStatusGroupIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/generate-scripts': {
      id: '/api/public/generate-scripts'
      path: '/api/public/generate-scripts'
      fullPath: '/api/public/generate-scripts'
      preLoaderRoute: typeof ApiPublicGenerateScriptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/extract-url': {
      id: '/api/public/extract-url'
      path: '/api/public/extract-url'
      fullPath: '/api/public/extract-url'
      preLoaderRoute: typeof ApiPublicExtractUrlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/heygen/voices': {
      id: '/api/public/heygen/voices'
      path: '/api/public/heygen/voices'
      fullPath: '/api/public/heygen/voices'
      preLoaderRoute: typeof ApiPublicHeygenVoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/heygen/generate-with-audio': {
      id: '/api/public/heygen/generate-with-audio'
      path: '/api/public/heygen/generate-with-audio'
      fullPath: '/api/public/heygen/generate-with-audio'
      preLoaderRoute: typeof ApiPublicHeygenGenerateWithAudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/heygen/generate': {
      id: '/api/public/heygen/generate'
      path: '/api/public/heygen/generate'
      fullPath: '/api/public/heygen/generate'
      preLoaderRoute: typeof ApiPublicHeygenGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/heygen/avatars': {
      id: '/api/public/heygen/avatars'
      path: '/api/public/heygen/avatars'
      fullPath: '/api/public/heygen/avatars'
      preLoaderRoute: typeof ApiPublicHeygenAvatarsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/elevenlabs/transcribe': {
      id: '/api/public/elevenlabs/transcribe'
      path: '/api/public/elevenlabs/transcribe'
      fullPath: '/api/public/elevenlabs/transcribe'
      preLoaderRoute: typeof ApiPublicElevenlabsTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/elevenlabs/clone-voice': {
      id: '/api/public/elevenlabs/clone-voice'
      path: '/api/public/elevenlabs/clone-voice'
      fullPath: '/api/public/elevenlabs/clone-voice'
      preLoaderRoute: typeof ApiPublicElevenlabsCloneVoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/heygen/status/$videoId': {
      id: '/api/public/heygen/status/$videoId'
      path: '/api/public/heygen/status/$videoId'
      fullPath: '/api/public/heygen/status/$videoId'
      preLoaderRoute: typeof ApiPublicHeygenStatusVideoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/heygen/photo-avatar/create': {
      id: '/api/public/heygen/photo-avatar/create'
      path: '/api/public/heygen/photo-avatar/create'
      fullPath: '/api/public/heygen/photo-avatar/create'
      preLoaderRoute: typeof ApiPublicHeygenPhotoAvatarCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/heygen/photo-avatar/status/$groupId': {
      id: '/api/public/heygen/photo-avatar/status/$groupId'
      path: '/api/public/heygen/photo-avatar/status/$groupId'
      fullPath: '/api/public/heygen/photo-avatar/status/$groupId'
      preLoaderRoute: typeof ApiPublicHeygenPhotoAvatarStatusGroupIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicExtractUrlRoute: ApiPublicExtractUrlRoute,
  ApiPublicGenerateScriptsRoute: ApiPublicGenerateScriptsRoute,
  ApiPublicElevenlabsCloneVoiceRoute: ApiPublicElevenlabsCloneVoiceRoute,
  ApiPublicElevenlabsTranscribeRoute: ApiPublicElevenlabsTranscribeRoute,
  ApiPublicHeygenAvatarsRoute: ApiPublicHeygenAvatarsRoute,
  ApiPublicHeygenGenerateRoute: ApiPublicHeygenGenerateRoute,
  ApiPublicHeygenGenerateWithAudioRoute: ApiPublicHeygenGenerateWithAudioRoute,
  ApiPublicHeygenVoicesRoute: ApiPublicHeygenVoicesRoute,
  ApiPublicHeygenPhotoAvatarCreateRoute: ApiPublicHeygenPhotoAvatarCreateRoute,
  ApiPublicHeygenStatusVideoIdRoute: ApiPublicHeygenStatusVideoIdRoute,
  ApiPublicHeygenPhotoAvatarStatusGroupIdRoute:
    ApiPublicHeygenPhotoAvatarStatusGroupIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
