/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicGenerateScriptsRouteImport } from './routes/api/public/generate-scripts'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGenerateScriptsRoute =
  ApiPublicGenerateScriptsRouteImport.update({
    id: '/api/public/generate-scripts',
    path: '/api/public/generate-scripts',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/generate-scripts': typeof ApiPublicGenerateScriptsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/generate-scripts': typeof ApiPublicGenerateScriptsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/generate-scripts': typeof ApiPublicGenerateScriptsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/public/generate-scripts'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/public/generate-scripts'
  id: '__root__' | '/' | '/api/public/generate-scripts'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicGenerateScriptsRoute: typeof ApiPublicGenerateScriptsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/generate-scripts': {
      id: '/api/public/generate-scripts'
      path: '/api/public/generate-scripts'
      fullPath: '/api/public/generate-scripts'
      preLoaderRoute: typeof ApiPublicGenerateScriptsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicGenerateScriptsRoute: ApiPublicGenerateScriptsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
